### ISSUE TITLE
Ability to save input when clicking outside of the table [Sponsored: Due Feb 1]

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#308]
Currently, if you are editing a value in the table, clicking outside of the table will not save persist the value.

**Comment by Marc-Andre-Rivet** [comment]
@chriddyp I've tried this on 3.1.11 and it seems to be persisting the value correctly when clicking outside the table. I've been using this small Dash app as a base https://github.com/plotly/dash-table/blob/master/tests/cypress/dash/v_be_page.py and added a dcc.Input(id="input", value="Foo") -- when clicking in either the body or the added input. Tested with input fields only, as dropdown fields are not subject to this problem (auto-closes  / apply value on selection).

The cell implementation has been extensively refactored in December, so the issue was possibly resolved during the refactor (https://github.com/plotly/dash-table/pull/281)?

Can you confirm if you are still experiencing this issue and provide an example if that's the case. Thanks.

**Comment by chriddyp** [comment]
I can't replicate this anymore, looks fixed now 🎉

**Comment by choprashweta** [comment]
I am still facing this issue with Dash Table 4.7.0 after double-clicking inside the cell before entering values. Upon clicking outside or clicking a button, the entered values do not persist. Issue has been illustrated here: https://community.plotly.com/t/double-click-the-input-field-in-dashtable-then-use-a-button-to-save-the-content-will-loss/25292
